spring.application.name=spring-data-jpa-hql-permanent-employees
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn_hql

spring.datasource.username=root

spring.datasource.password=sar1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=9090